import "./globals.scss";
import { Inter } from "next/font/google";

import Image from "next/image";
import Button from "@mui/material/Button";
import GNB from "./components/GNB";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GNB />
        {children}
      </body>
    </html>
  );
}
